### PR TITLE
Resync Steering command added

### LINKED ISSUE #102: Resyncing steer encoders on the fly
We need to be able to re-sync the steering encoders on the fly in case something goes wrong.

We already have code to do this but we have to be careful to not mess up anything else.

Tasks:

- [ ] Create a command to SyncSteerOnTheFly. This should have code in initlize() and then immedialty return true to isFinished()
- [ ] Call the resetEncodersFromCanCoder method in SwerveSubsystem
- [ ] After resetEncodersFromCanCoder, call resetLastAngles method in SwerveSubsystem. This will make sure the lastAngle variables are updated properly after syncing.
- [ ] Store the current odometry value before resetting the encoders. Then after resetting, call resetOdometry to put back this value.
- [ ] Bind to a button on driver controller. This should probably go on the start button and the cone driver aid that's there should be moved to another button. Start button is good because it's hard to accidently press (which might mess things up if used at the wrong time)

### PR DESCRIPTION
**Pull request by lchangGH**
Closes #102

### CODE REVIEW

File: src/main/java/frc/robot/commands/SyncSteerOnFly.java [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+package frc.robot.commands;
+
+import edu.wpi.first.math.geometry.Pose2d;
+import edu.wpi.first.wpilibj2.command.CommandBase;
+import frc.robot.subsystems.SwerveSubsystem;
+
+public class SyncSteerOnFly extends CommandBase {
+  /** Creates a new SyncSteerOnFly. */
+  public SyncSteerOnFly() {
+    // Use addRequirements() here to declare subsystem dependencies.
```
Comment (weizhang-2706) [inline src/main/java/frc/robot/commands/SyncSteerOnFly.java:14]: you probably need to add SwerveSubsystem.getInstance() as a requirement.

**Review by weizhang-2706 — CHANGES_REQUESTED** [review]

File: src/main/java/frc/robot/commands/SyncSteerOnFly.java (hunk 1 above)
Comment (ErikCald) [reply src/main/java/frc/robot/commands/SyncSteerOnFly.java:14]: Adding that requirement would unscheduled TeleopSwerve for one roborio cycle, which may be a good thing because this command should not be used the chassis is moving.

I agree with adding the requirement

**Review by ErikCald — APPROVED** [review]

**Review by weizhang-2706 — APPROVED** [review]
